=== gems-uff/prov-viewer/src/main/resources/SimilarityConfig/similarityConfig.xsd
<?xml version="1.0"?>
<!--
Copyright (C) 2017 Kohwalter

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="config" type="configuration"/>
    
    <!-- Configuration Type -->
    <xs:complexType name="configuration">
        <xs:sequence>
            <!--  -->
            <xs:element name="similarityThreshold" type="xs:decimal"/>
            <!-- The default  -->
            <xs:element name="default_error" type="xs:string"/>
            <!--  -->
            <xs:element name="attributeErrorList" type="attribute" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Attribute threshold -->
    <xs:complexType name="attribute">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <!-- Take MAX value or MEAN value for each edge type -->
            <xs:element name="value" type="xs:string"/>
            <!-- Collapse function used: True = multiplication; False = Add -->
            <xs:element name="weight" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== gems-uff/prov-viewer/src/main/resources/SimilarityConfig/AngryBotsMergeConfigExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License

Copyright 2017 Kohwalter.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->


<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='similarityConfig.xsd'>
    <similarityThreshold>0.95f</similarityThreshold>
    <default_error>5%</default_error>
    <default_weight>1</default_weight>
    <attributeErrorList>
        <name>ObjectPosition_X</name>
        <value>5%</value>
        <weight>1</weight>
    </attributeErrorList>
    <attributeErrorList>
        <name>ObjectPosition_Y</name>
        <value>5%</value>
        <weight>1</weight>
    </attributeErrorList>
    <attributeErrorList>
        <name>ObjectPosition_Z</name>
        <value>5%</value>
        <weight>1</weight>
    </attributeErrorList>

</config>
