=== gems-uff/prov-viewer/src/main/resources/Config/config.xsd
<?xml version="1.0"?>
<!--
The MIT License

Copyright 2017 Kohwalter.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="config" type="configuration"/>
    
    <!-- Configuration Type -->
    <xs:complexType name="configuration">
        <xs:sequence>
            <!-- Define the vertex size in the graph. Default value is 15 -->
            <xs:element name="vertexSize" type="xs:string"/>
            <!-- Define the timeScale used in the timestamps: Nanoseconds, Microseconds, Milliseconds, Seconds, Minutes, Hours, Days, Weeks, SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss") -->
            <xs:element name="timeScale" type="xs:string"/> 
            <!-- The default layout used when loading the program -->
            <xs:element name="default_layout" type="xs:string"/>
            <!--Temporal layout parameters-->
            <xs:element name="temporalLayout" type="temporalLayout" minOccurs="1" maxOccurs="1"/>
            <!--Spatial layout parameters-->
            <xs:element name="spatialLayout" type="spatialLayout" minOccurs="1" maxOccurs="1"/>
            <!-- List of all edges and their configuration values -->
            <xs:element name="edgetype" type="edgetype" minOccurs="0" maxOccurs="unbounded"/>
            <!-- List of all vertices labels for filtering -->
            <xs:element name="vertexAttributeFilter" type="vertexAttributeFilter" minOccurs="0" maxOccurs="unbounded"/>
            <!-- List of all display modes -->
            <xs:element name="colorscheme" type="colorscheme" minOccurs="0" maxOccurs="unbounded"/>
            <!-- List of all special vertices that has different stroke -->
            <xs:element name="vertexstroke" type="vertexstroke" minOccurs="0" maxOccurs="unbounded"/>
            <!-- List of types of activity vertex and their configuration values -->
            <xs:element name="vertexcolor" type="vertexcolor" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
  
    <!-- String List -->
    <xs:simpleType name="stringlist">
        <xs:list itemType="xs:string"/>
    </xs:simpleType>
    
    <xs:complexType name="temporalLayout">
        <xs:sequence>
            <!-- Temporal Layout backbone vertex type -->
            <xs:element name="temporalLayoutbackbone" type="xs:string"/>
            <!-- Temporal Layout scale -->
            <xs:element name="temporalLayoutscale" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="spatialLayout">
        <xs:sequence>
            <!-- Spatial Layout X axis name -->
            <xs:element name="layoutAxis_X" type="xs:string"/>
            <!-- Spatial Layout Y axis name -->
            <xs:element name="layoutAxis_Y" type="xs:string"/>
            <!-- Spatial Layout Background Image location -->
            <xs:element name="imageLocation" type="xs:string"/>
            <!-- Spatial Layout Camera X position -->
            <xs:element name="imageOffset_X" type="xs:string"/>
            <!-- Spatial Layout Camera Y position -->
            <xs:element name="imageOffset_Y" type="xs:string"/>
            <!-- Spatial Layout Camera's upper left corner of the screen position in relation to the camera -->
            <xs:element name="spatialLayoutPosition" type="xs:string"/>
            <!-- Spatial Layout parameter used for Google Maps or OpenStreetMap image. Set value to zero if not using Google Maps image -->
            <xs:element name="zoomLevel" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
        
    <!-- Edge Type -->
    <xs:complexType name="edgetype">
        <xs:sequence>
            <xs:element name="edge" type="xs:string"/>
            <!-- Take MAX value or MEAN value for each edge type -->
            <xs:element name="edgestroke" type="xs:string"/>
            <!-- Collapse function used: True = multiplication; False = Add -->
            <xs:element name="collapsefunction" type="xs:string"/>
            <!-- Define if the color scheme for the edge is inverted (Inverted: Red = positive values, Green = negative values) -->
            <xs:element name="isInverted" type="xs:string"/>
            <!--Define the special color for this edge type-->
            <xs:element name="edgeColor" type="color"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Vertex Label Filter -->
    <xs:complexType name="vertexAttributeFilter">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
      
    <!-- Special Vertex Stroke -->
    <xs:complexType name="vertexstroke">
        <xs:sequence>
            <xs:element name="attribute" type="xs:string"/>
            <xs:element name="values" type="stringlist"/>
        </xs:sequence>
    </xs:complexType>  
    
    <!-- Mode Type -->
    <xs:complexType name="colorscheme">
        <xs:sequence>
            <xs:element name="attribute" type="xs:string"/>
            <xs:element name="class" type="xs:string"/>
            <xs:element name="trafficLightType" type="xs:string"/>
            <xs:element name="isInverted" type="xs:string"/>
            <xs:element name="values" type="stringlist"/>
            <xs:element name="goodvalue" type="xs:decimal" minOccurs="0" maxOccurs="1"/>
            <xs:element name="badvalue" type="xs:decimal" minOccurs="0" maxOccurs="1"/>
            <xs:element name="restrictedAttribute" type="stringlist"/>
            <xs:element name="restrictedValue" type="stringlist"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="vertexcolor">
        <xs:sequence>
            <xs:element name="generalname" type="xs:string"/>
            <xs:element name="activitycolor" type="activitycolor" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="entitycolor" type="entitycolor" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="agentcolor" type="agentcolor" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- Activity Vertex Type -->
    <xs:complexType name="activitycolor">
        <xs:sequence>
            <xs:element name="attribute" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
            <xs:element name="vercolor" type="color"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="entitycolor">
        <xs:sequence>
            <xs:element name="attribute" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
            <xs:element name="vercolor" type="color"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="agentcolor">
        <xs:sequence>
            <xs:element name="attribute" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
            <xs:element name="vercolor" type="color"/>
        </xs:sequence>
    </xs:complexType>
        
<!-- Color Type -->
<xs:complexType name="color">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="r" type="xs:integer"/>
        <xs:element name="g" type="xs:integer"/>
        <xs:element name="b" type="xs:integer"/>
    </xs:sequence>
</xs:complexType>

</xs:schema>

=== gems-uff/prov-viewer/src/main/resources/Config/2D_Tower_Defense_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License

Copyright 2017 Kohwalter.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->


<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='config.xsd'>
    <default_layout>FRLayout</default_layout>
    <layoutAxis_X>ObjectPosition_X</layoutAxis_X>
    <layoutAxis_Y>ObjectPosition_Y</layoutAxis_Y>
    <imageLocation>/images/2D_Defense.png</imageLocation>
    <imageOffset_X>-4.428253</imageOffset_X>
    <imageOffset_Y>-10</imageOffset_Y>
    <spatialLayoutPosition>-18.5228</spatialLayoutPosition>
    <zoomLevel>0</zoomLevel>
    <temporalLayoutbackbone>Player</temporalLayoutbackbone>
    <temporalLayoutscale>0.5</temporalLayoutscale>
    <edgetype>
        <edge>Neutral</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>None</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Health (Player)</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Health (Enemy)</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Score</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Health</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Bomb</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <colorscheme>
        <attribute>Health</attribute>
        <class>ActivityScheme</class>
        <values></values>
        <goodvalue></goodvalue>
        <badvalue></badvalue>
    </colorscheme>
    <colorscheme>
        <attribute>Score</attribute>
        <class>ActivityScheme</class>
        <values></values>
        <goodvalue></goodvalue>
        <badvalue></badvalue>
    </colorscheme>
    <colorscheme>
        <attribute>Health</attribute>
        <class>ActivityRestrictedScheme</class>
        <values></values>
        <goodvalue>100</goodvalue>
        <badvalue>0</badvalue>
        <restrictedAttribute>ObjectName</restrictedAttribute>
        <restrictedValue>hero</restrictedValue>
    </colorscheme>
    <vertexstroke>
        <attribute>Health</attribute>
        <values>0</values>
    </vertexstroke>
    <activitycolor>
        <attribute>Health</attribute>
        <value>0</value>
        <vercolor>
            <r>255</r>
            <g>180</g>
            <b>180</b>
        </vercolor>
    </activitycolor>


</config>

=== gems-uff/prov-viewer/src/main/resources/Config/Reprozip_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='config.xsd'>
    <default_layout>TimelineLayout</default_layout>
    <vertexAttributeFilter>Subtype</vertexAttributeFilter>
    <layoutAxis_X>ObjectPosition_X</layoutAxis_X>
    <layoutAxis_Y>ObjectPosition_Y</layoutAxis_Y>
    <imageLocation></imageLocation>
    <imageOffset_X>0</imageOffset_X>
    <imageOffset_Y>0</imageOffset_Y>
    <spatialLayoutPosition>0.0</spatialLayoutPosition>
    <zoomLevel>0</zoomLevel>
    <temporalLayoutscale>1.0</temporalLayoutscale>
    <temporalLayoutbackbone></temporalLayoutbackbone>
    <edgetype>
        <edge>RunStarts</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>PerformsFork</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>ForkCreates</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>PerformsFileAccess</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>AccessFile</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>ProcessExecution</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>ExecutionFile</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <vertexvaluefilter>
        <value>Run</value>
    </vertexvaluefilter>
    <vertexvaluefilter>
        <value>Process</value>
    </vertexvaluefilter>
    <vertexvaluefilter>
        <value>File</value>
    </vertexvaluefilter>
    <vertexvaluefilter>
        <value>Directory</value>
    </vertexvaluefilter>
    <vertexvaluefilter>
        <value>Fork</value>
    </vertexvaluefilter>
    <vertexvaluefilter>
        <value>FileWrites</value>
    </vertexvaluefilter>
    <vertexvaluefilter>
        <value>FileReads</value>
    </vertexvaluefilter>
    <vertexvaluefilter>
        <value>ProcessExecutes</value>
    </vertexvaluefilter>
</config>

=== gems-uff/prov-viewer/src/main/resources/Angry_Robots_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='config.xsd'>
    <layoutbackbone>Player</layoutbackbone>
	<layoutAxis_X>ObjectPosition_X</layoutAxis_X>
	<layoutAxis_Y>ObjectPosition_Z</layoutAxis_Y>
	<coordinatesLayoutScale>25</coordinatesLayoutScale>
	<temporalLayoutscale>0.5</temporalLayoutscale>
	<showentitydate>false</showentitydate>
    <edgetype>
        <edge>Neutral</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>None</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Health (Player)</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Health (Enemy)</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Score</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Health</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Unlocked</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Interacted</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Respawned</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <colorscheme>
        <attribute>Health</attribute>
        <class>ActivityScheme</class>
        <values></values>
        <goodvalue></goodvalue>
        <badvalue></badvalue>
    </colorscheme>
	<colorscheme>
        <attribute>Health</attribute>
        <class>ActivityRestrictedScheme</class>
        <values></values>
        <goodvalue>100</goodvalue>
        <badvalue>0</badvalue>
		<restrictedAttribute>ObjectName</restrictedAttribute>
        <restrictedValue>Player</restrictedValue>
    </colorscheme>
    <colorscheme>
        <attribute>Score</attribute>
        <class>ActivityScheme</class>
        <values></values>
        <goodvalue></goodvalue>
        <badvalue></badvalue>
    </colorscheme>
    <vertexstroke>
        <attribute>ObjectName</attribute>
        <values>Player</values>
    </vertexstroke>
    <activitycolor>
        <attribute>Health</attribute>
        <value>0</value>
        <vercolor>
            <r>255</r>
            <g>180</g>
            <b>180</b>
        </vercolor>
    </activitycolor>
	<activitycolor>
        <attribute>ObjectName</attribute>
        <value>Player</value>
        <vercolor>
            <r>0</r>
            <g>255</g>
            <b>0</b>
        </vercolor>
    </activitycolor>
	<activitycolor>
        <attribute>ObjectName</attribute>
        <value>KamikazeBuzzer</value>
        <vercolor>
            <r>255</r>
            <g>155</g>
            <b>0</b>
        </vercolor>
    </activitycolor>
	<activitycolor>
        <attribute>ObjectName</attribute>
        <value>EnemySpider</value>
        <vercolor>
            <r>255</r>
            <g>0</g>
            <b>155</b>
        </vercolor>
    </activitycolor>
	<activitycolor>
        <attribute>ObjectName</attribute>
        <value>EnemyMech</value>
        <vercolor>
            <r>255</r>
            <g>150</g>
            <b>100</b>
        </vercolor>
    </activitycolor>


</config>

=== gems-uff/prov-viewer/src/main/resources/2D_Provenance_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='config.xsd'>
    <layoutbackbone>Player</layoutbackbone>
	<layoutAxis_X>ObjectPosition_X</layoutAxis_X>
	<layoutAxis_Y>ObjectPosition_Z</layoutAxis_Y>
	<imageLocation></imageLocation>
	<imageOffset_X>0.55</imageOffset_X>
	<imageOffset_Y>0.81</imageOffset_Y>
	<coordinatesLayoutPosition>10</coordinatesLayoutPosition>
	<temporalLayoutscale>0.5</temporalLayoutscale>
	<showentitydate>false</showentitydate>
    <edgetype>
        <edge>Neutral</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>None</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Health (Player)</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Health (Enemy)</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Score</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Health</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
	<edgetype>
        <edge>Bomb</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <colorscheme>
        <attribute>Health</attribute>
        <class>ActivityScheme</class>
        <values></values>
        <goodvalue></goodvalue>
        <badvalue></badvalue>
    </colorscheme>
    <colorscheme>
        <attribute>Score</attribute>
        <class>ActivityScheme</class>
        <values></values>
        <goodvalue></goodvalue>
        <badvalue></badvalue>
    </colorscheme>
    <vertexstroke>
        <attribute>Health</attribute>
        <values>0</values>
    </vertexstroke>
    <activitycolor>
        <attribute>Health</attribute>
        <value>0</value>
        <vercolor>
            <r>255</r>
            <g>180</g>
            <b>180</b>
        </vercolor>
    </activitycolor>


</config>

=== gems-uff/prov-viewer/src/main/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='config.xsd'>
    <layoutbackbone>Project</layoutbackbone>
    <edgetype>
        <edge>Neutral</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Credits</edge>
        <edgestroke>MEAN</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Quality</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Progress</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Aid</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>AVERAGE</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Val</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Discovery</edge>
        <edgestroke>true</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Repair</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Bug</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>TC</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Morale</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Stamina</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Prototype</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>Negotiation</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <colorscheme>
        <attribute>Morale</attribute>
        <class>ActivityScheme</class>
        <values></values>
        <maxvalue>100</maxvalue>
        <minvalue>0</minvalue>
    </colorscheme>
    <colorscheme>
        <attribute>Stamina</attribute>
        <class>ActivityScheme</class>
        <values></values>
        <maxvalue></maxvalue>
        <minvalue></minvalue>
    </colorscheme>
    <colorscheme>
        <attribute>Hours</attribute>
        <class>ActivityInvertedLimitedScheme</class>
        <values></values>
        <maxvalue>16</maxvalue>
        <minvalue>0</minvalue>
    </colorscheme>
    <colorscheme>
        <attribute>Credits</attribute>
        <class>EntityScheme</class>
        <values></values>
        <maxvalue></maxvalue>
        <minvalue></minvalue>
    </colorscheme>
    <colorscheme>
        <attribute>Role</attribute>
        <class>ActivityMultiScheme</class>
        <values>Analyst Architect Manager Marketing Programmer Tester</values>
        <maxvalue></maxvalue>
        <minvalue></minvalue>
    </colorscheme>
    <colorscheme>
        <attribute>Weekend</attribute>
        <class>WeekendScheme</class>
        <values>Sat Sun</values>
        <maxvalue></maxvalue>
        <minvalue></minvalue>
    </colorscheme>
    <vertexstroke>
        <attribute>Role</attribute>
        <values>Idle Fired Promotion Training Hired"</values>
    </vertexstroke>
    <activitycolor>
        <attribute>Task</attribute>
        <value>Idle</value>
        <vercolor>
            <r>238</r>
            <g>180</g>
            <b>180</b>
        </vercolor>
    </activitycolor>
    <activitycolor>
        <attribute>Role</attribute>
        <value>Training</value>
        <vercolor>
            <r>102</r>
            <g>0</g>
            <b>102</b>
        </vercolor>
    </activitycolor>
    <activitycolor>
        <attribute>Task</attribute>
        <value>Fired</value>
        <vercolor>
            <r>139</r>
            <g>69</g>
            <b>19</b>
        </vercolor>
    </activitycolor>
    <activitycolor>
        <attribute>Task</attribute>
        <value>Promotion</value>
        <vercolor>
            <r>0</r>
            <g>153</g>
            <b>0</b>
        </vercolor>
    </activitycolor>
    <activitycolor>
        <attribute>Task</attribute>
        <value>Hired</value>
        <vercolor>
            <r>139</r>
            <g>136</g>
            <b>120</b>
        </vercolor>
    </activitycolor>
    <activitycolor>
        <attribute>Task</attribute>
        <value>Negotiation</value>
        <vercolor>
            <r>193</r>
            <g>205</g>
            <b>193</b>
        </vercolor>
    </activitycolor>

</config>

=== gems-uff/prov-viewer/src/main/resources/bus_config.xml
<?xml version="1.0" encoding="UTF-8"?>

<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='config.xsd'>
    <layoutbackbone>Player</layoutbackbone>
	<layoutAxis_X>ObjectPosition_X</layoutAxis_X>
	<layoutAxis_Y>ObjectPosition_Y</layoutAxis_Y>
	<imageLocation>/images/BusMap.png</imageLocation>
	<imageOffset_X>-43.2206256</imageOffset_X>
	<imageOffset_Y>-22.9072658</imageOffset_Y>
	<coordinatesLayoutPosition>-0.0586224</coordinatesLayoutPosition>
	
	<temporalLayoutscale>-10000000.5</temporalLayoutscale>
	<showentitydate>false</showentitydate>
    <edgetype>
        <edge>Cronological</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <colorscheme>
        <attribute>VELOCIDADE</attribute>
        <class>ActivityScheme</class>
        <values></values>
        <goodvalue></goodvalue>
        <badvalue></badvalue>
    </colorscheme>	
    <activitycolor>
        <attribute>LINHA</attribute>
        <value>47</value>
        <vercolor>
            <r>255</r>
            <g>180</g>
            <b>180</b>
        </vercolor>
    </activitycolor>
</config>

=== gems-uff/prov-viewer/src/main/resources/Config/PROV_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='config.xsd'>
    <layoutbackbone></layoutbackbone>
    <default_layout>FRLayout</default_layout>
    <layoutAxis_X>ObjectPosition_X</layoutAxis_X>
    <layoutAxis_Y>ObjectPosition_Y</layoutAxis_Y>
    <imageLocation></imageLocation>
    <imageOffset_X>0</imageOffset_X>
    <imageOffset_Y>0</imageOffset_Y>
    <spatialLayoutPosition>0.0</spatialLayoutPosition>
	<googleZoomLevel>0</googleZoomLevel>
    <temporalLayoutscale>1.0</temporalLayoutscale>
    <showentitydate>true</showentitydate>
    <showentitylabel>true</showentitylabel>
    <edgetype>
        <edge>wasDerivedFrom</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>used</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>wasGeneratedBy</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>wasInformedBy</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>wasAttributedTo</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>wasAssociatedWith</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
    <edgetype>
        <edge>actedOnBehalfOf</edge>
        <edgestroke>MAX</edgestroke>
        <collapsefunction>SUM</collapsefunction>
    </edgetype>
</config>
