=== gems-uff/prov-viewer/src/main/resources/Graph/input.xsd
<?xml version="1.0"?>
<!--
The MIT License

Copyright 2017 Kohwalter.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="provenancedata" type="provdata"/>
    
    <!-- Configuration Type -->
    <xs:complexType name="provdata">
        <xs:sequence>
            <!-- List of all vertices and their configuration values -->
            <xs:element name="vertices" type="vertices" minOccurs="1" maxOccurs="1"/>
            <!-- List of all edges and their configuration values -->
            <xs:element name="edges" type="edges" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
	
	<!-- Vertex List -->
    <xs:complexType name="vertices">
        <xs:sequence>
            <xs:element name="vertex" type="vertex" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
	
	<!-- Edges List -->
	<xs:complexType name="edges">
        <xs:sequence>
            <xs:element name="edge" type="edge" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
	
    <!-- Edge Type -->
    <xs:complexType name="edge">
        <xs:sequence>
            <!-- Edge unique ID -->
            <xs:element name="ID" type="xs:string"/>
            <!-- Edge type -->
            <xs:element name="type" type="xs:string"/>
            <!-- Edge label -->
            <xs:element name="label" type="xs:string"/>
            <!-- Edge value -->
            <xs:element name="value" type="xs:string"/>
            <!-- Source vertex's unique ID -->
            <xs:element name="sourceID" type="xs:string"/>
            <!-- Target vertex's unique ID -->
            <xs:element name="targetID" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Vertex Node -->
    <xs:complexType name="vertex">
        <xs:sequence>
            <!-- Vertex unique ID -->
            <xs:element name="ID" type="xs:string"/>
            <!-- Vertex type (Activity, Entity, Agent) -->
            <xs:element name="type" type="xs:string"/>
            <!-- Vertex label -->
            <xs:element name="label" type="xs:string"/>
            <!-- Vertex Date of Creation/Appearance -->
            <xs:element name="date" type="xs:string"/>
            <!-- Vertex Attributes -->
            <xs:element name="attributes" type="attributes" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
	<!-- Attribute List -->
    <xs:complexType name="attributes">
        <xs:sequence>
            <xs:element name="attribute" type="vertexattribute" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
	
    <!-- Special Vertex Stroke -->
    <xs:complexType name="vertexattribute">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>  

</xs:schema>

=== gems-uff/prov-viewer/src/main/resources/Map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<provenancedata
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='input.xsd'>
	<vertex>
        <ID>ent0</ID>
        <type>Entity</type>
        <label>Village</label>
        <date>0</date>
        <attributes>
			<attribute>  
				<name>ObjectPosition_X</name>
				<value>0</value>
			</attribute>
			<attribute>
				<name>ObjectPosition_Y</name>
				<value>0</value>
			</attribute>
		</attributes>
    </vertex>
	<vertex>
        <ID>ent1</ID>
        <type>Entity</type>
        <label>Forest</label>
        <date>1</date>
        <attributes>
			<attribute>  
				<name>ObjectPosition_X</name>
				<value>2</value>
			</attribute>
			<attribute>
				<name>ObjectPosition_Y</name>
				<value>3</value>
			</attribute>
		</attributes>
    </vertex>
	<vertex>
        <ID>ent2</ID>
        <type>Entity</type>
        <label>Village</label>
        <date>2</date>
        <attributes>
			<attribute>  
				<name>ObjectPosition_X</name>
				<value>0</value>
			</attribute>
			<attribute>
				<name>ObjectPosition_Y</name>
				<value>0</value>
			</attribute>
		</attributes>
    </vertex>
	<vertex>
        <ID>ent3</ID>
        <type>Entity</type>
        <label>Dungeon</label>
        <date>3</date>
        <attributes>
			<attribute>  
				<name>ObjectPosition_X</name>
				<value>3</value>
			</attribute>
			<attribute>
				<name>ObjectPosition_Y</name>
				<value>0</value>
			</attribute>
		</attributes>
    </vertex>
	<vertex>
        <ID>ent4</ID>
        <type>Entity</type>
        <label>Plains</label>
        <date>4</date>
        <attributes>
			<attribute>  
				<name>ObjectPosition_X</name>
				<value>5</value>
			</attribute>
			<attribute>
				<name>ObjectPosition_Y</name>
				<value>1</value>
			</attribute>
		</attributes>
    </vertex>
	<vertex>
        <ID>ent5</ID>
        <type>Entity</type>
        <label>Town</label>
        <date>5</date>
        <attributes>
			<attribute>  
				<name>ObjectPosition_X</name>
				<value>6</value>
			</attribute>
			<attribute>
				<name>ObjectPosition_Y</name>
				<value>-1</value>
			</attribute>
		</attributes>
    </vertex>
    <edge>
        <ID>e0</ID>
        <label>Neutral</label>
        <type>wlabelerivedFrom</type>
        <value></value>
        <sourceID>ent1</sourceID>
        <targetID>ent0</targetID>
    </edge>
	<edge>
        <ID>e1</ID>
        <label>Neutral</label>
        <type>wlabelerivedFrom</type>
        <value></value>
        <sourceID>ent2</sourceID>
        <targetID>ent1</targetID>
    </edge>
	<edge>
        <ID>e2</ID>
        <label>Neutral</label>
        <type>wlabelerivedFrom</type>
        <value></value>
        <sourceID>ent3</sourceID>
        <targetID>ent2</targetID>
    </edge>
	<edge>
        <ID>e3</ID>
        <label>Neutral</label>
        <type>wlabelerivedFrom</type>
        <value></value>
        <sourceID>ent4</sourceID>
        <targetID>ent3</targetID>
    </edge>
	<edge>
        <ID>e4</ID>
        <label>Neutral</label>
        <type>wlabelerivedFrom</type>
        <value></value>
        <sourceID>ent5</sourceID>
        <targetID>ent4</targetID>
    </edge>
</provenancedata>

=== gems-uff/prov-viewer/src/main/resources/Graph/Inference_Example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<provenancedata
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='input.xsd'>
	<vertex>
        <ID>ent0</ID>
        <type>Entity</type>
        <label>Project</label>
        <date>0</date>
        <attribute>
            <name>Deadline</name>
            <value>32</value>
        </attribute>
	<attribute>
            <name>ProgrammingLanguage</name>
            <value>java</value>
        </attribute>
	<attribute>
            <name>Payment</name>
            <value>15000</value>
        </attribute>
        <attribute>
            <name>Credits</name>
            <value>40000</value>
        </attribute>
    </vertex>
	<vertex>
        <ID>ent1</ID>
        <type>Entity</type>
        <label>Project</label>
        <date>1</date>
        <attribute>
            <name>Deadline</name>
            <value>32</value>
        </attribute>
	<attribute>
            <name>ProgrammingLanguage</name>
            <value>java</value>
        </attribute>
	<attribute>
            <name>Payment</name>
            <value>15000</value>
        </attribute>
        <attribute>
            <name>Credits</name>
            <value>39791</value>
        </attribute>
    </vertex>
	<vertex>
        <ID>ent2</ID>
        <type>Entity</type>
        <label>Project</label>
        <date>2</date>
        <attribute>
            <name>Deadline</name>
            <value>32</value>
        </attribute>
	<attribute>
            <name>ProgrammingLanguage</name>
            <value>java</value>
        </attribute>
	<attribute>
            <name>Payment</name>
            <value>15000</value>
        </attribute>
        <attribute>
            <name>Credits</name>
            <value>30011</value>
        </attribute>
    </vertex>
	<vertex>
        <ID>ent3</ID>
        <type>Entity</type>
        <label>Project</label>
        <date>3</date>
        <attribute>
            <name>Deadline</name>
            <value>32</value>
        </attribute>
    </vertex>
	<vertex>
        <ID>ent4</ID>
        <type>Entity</type>
        <label>Project</label>
        <date>4</date>
        <attribute>
            <name>Deadline</name>
            <value>32</value>
        </attribute>
    </vertex>
    <edge>
        <ID>e0</ID>
        <label>Neutral</label>
        <type>wlabelerivedFrom</type>
        <value></value>
        <sourceID>ent1</sourceID>
        <targetID>ent0</targetID>
    </edge>
	<edge>
        <ID>e1</ID>
        <label>Neutral</label>
        <type>wlabelerivedFrom</type>
        <value></value>
        <sourceID>ent2</sourceID>
        <targetID>ent1</targetID>
    </edge>
	<edge>
        <ID>e2</ID>
        <label>Neutral</label>
        <type>wlabelerivedFrom</type>
        <value></value>
        <sourceID>ent3</sourceID>
        <targetID>ent2</targetID>
    </edge>
	<edge>
        <ID>e3</ID>
        <label>Neutral</label>
        <type>wlabelerivedFrom</type>
        <value></value>
        <sourceID>ent4</sourceID>
        <targetID>ent3</targetID>
    </edge>
</provenancedata>
